### ISSUE TITLE
make deploy error

### ISSUE THREAD

**Issue by shivangi-aneja** [tbaltrushaitis/cv#20]
I get the following error when I run the command `make deploy` on my mac.
Am I missing something? There is some issue with the gulp file. But don't know what

```
cp: illegal option -- u
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- u
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
/bin/sh: md5sum: command not found
[01:03:07] Created file [BUILD-0.2.6:1]
[01:03:07] Created file [BUILD_CONTENT:/Users/shivangi/Desktop/cv/config/build.json]
[01:03:07] Created file [COMMIT:028e99202cc959a20f2d47cd10e05d4050b124f6]
[01:03:07] GOALS
[01:03:07]   \-- DEFAULT: [default]
[01:03:07]   \-- CURRENT: [deploy]
┌──────────────────────────────────────────────────────────────────────┐
│   ______     __    ____   ___  ____ _____ _____ ___  _     ___ ___   │
│  / ___\ \   / /_  |  _ \ / _ \|  _ \_   _|  ___/ _ \| |   |_ _/ _ \  │
│ | |    \ \ / /| |_| |_) | | | | |_) || | | |_ | | | | |    | | | | | │
│ | |___  \ V /_   _|  __/| |_| |  _ < | | |  _|| |_| | |___ | | |_| | │
│  \____|  \_/  |_| |_|    \___/|_| \_\|_| |_|   \___/|_____|___\___/  │
│                                                                      │
└──────────────────────────────────────────────────────────────────────┘
npm WARN deprecated bower@1.8.8: We don't recommend using Bower for new projects. Please consider Yarn and Webpack or Parcel. You can read how to migrate legacy project here: https://bower.io/blog/2017/how-to-migrate-away-from-bower/
/usr/local/nodejs/bin/bower -> /usr/local/nodejs/lib/node_modules/bower/bin/bower
+ bower@1.8.8
updated 1 package in 6.107s

> cv@0.2.5 preinstall /Users/shivangi/Desktop/cv
> echo [PRE-INSTALL] --- 

[PRE-INSTALL] ---

> cv@0.2.5 install /Users/shivangi/Desktop/cv
> echo [INSTALL] --- 

[INSTALL] ---

> cv@0.2.5 postinstall /Users/shivangi/Desktop/cv
> echo [POST-INSTALL] --- 

[POST-INSTALL] ---
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> cv@0.2.5 prepublish /Users/shivangi/Desktop/cv
> echo [PRE-PUBLISH] --- 

[PRE-PUBLISH] ---

> cv@0.2.5 prepare /Users/shivangi/Desktop/cv
> echo [PREPARE] --- 

[PREPARE] ---
npm WARN gulp-imagemin@7.1.0 requires a peer of gulp@>=4 but none is installed. You must install peer dependencies yourself.

audited 15429 packages in 18.888s
found 43 vulnerabilities (20 low, 6 moderate, 17 high)
  run `npm audit fix` to fix them, or `npm audit` for details
[01:03:07] FINISHED GOAL: [ setup-deps ]
[01:03:38] FINISHED GOAL: [ setup ]

> cv@0.2.5 prebuild /Users/shivangi/Desktop/cv
> echo [PRE-BUILD]; gulp populate --color

[PRE-BUILD]
fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/Users/shivangi/Desktop/cv/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/shivangi/Desktop/cv/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/shivangi/Desktop/cv/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:99)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cv@0.2.5 prebuild: `echo [PRE-BUILD]; gulp populate --color`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cv@0.2.5 prebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/shivangi/.npm/_logs/2020-04-27T23_03_42_261Z-debug.log
make: *** [build] Error 1
```

**Comment by tbaltrushaitis** [comment]
Hi!

This is duplicate.
Please take a look at the solution proposed in #19 

Kind Regards!

**Comment by tbaltrushaitis** [comment]
:heavy_check_mark: Due to starter inactivity
