### ISSUE TITLE
Dependency issue

### ISSUE THREAD

**Issue by akhilrajmailbox** [tbaltrushaitis/cv#46]
Can you please clarify which version fo NodeJS we have to use for creating the artefact ?
I tried the following steps with multiple version of Node, all are failing at step 4. 

1️⃣ Clone the repository
```coce
$ APP_NAME=cv \
&& git clone https://github.com/tbaltrushaitis/${APP_NAME}.git \
&& cd ${APP_NAME}
```

2️⃣ Install dependencies
```coce
$ make setup
```

3️⃣ Configure
```coce
Replace values in config/person.json with your personal information
```

4️⃣ Build
```coce
$ make build
```

**Comment by akhilrajmailbox** [comment]
I am trying with version 0.2.4 : Tag (v0.2.4), and the dev tools versions are ;
``code
# node -v
v8.0.0
# npm -v
5.0.0
```

But getting the following error:

```code
npm info it worked if it ends with ok
npm info using npm@5.0.0
npm info using node@v8.0.0
npm info lifecycle cv@0.2.4~prebuild: cv@0.2.4

> cv@0.2.4 prebuild /opt/cv
> echo [PRE-BUILD]; gulp populate --color

[PRE-BUILD]
/opt/cv/node_modules/find-up/index.js:29
                const foundPath = await runMatcher({...options, cwd: directory});
                                                    ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at pkgUp (/opt/cv/node_modules/yargs/yargs.js:537:20)
npm info lifecycle cv@0.2.4~prebuild: Failed to exec prebuild script
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cv@0.2.4 prebuild: `echo [PRE-BUILD]; gulp populate --color`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cv@0.2.4 prebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-06-02T05_26_55_973Z-debug.log
[05:26:53] FINISHED GOAL: [ build ]
```

**Comment by tbaltrushaitis** [comment]
Sorry, but we're not supporting outdated versions.
Please use the latest one.
