### ISSUE TITLE
make build - error

### ISSUE THREAD

**Issue by unisharpUO** [tbaltrushaitis/cv#61]
I'm getting this error during make build

`[17:17:53] Starting 'frontJS'...`
`[17:17:53] 'frontJS' errored after 8.62 ms`
`[17:17:53] Error: File not found with singular glob: /opt/temp/cv.git/build-0.3.1-8-production/resources/assets/js/lib/jquery.js (if this was purposeful, use `allowEmpty` option)
    at Glob.<anonymous> (/opt/temp/cv.git/node_modules/glob-stream/readable.js:84:17)
    at Object.onceWrapper (node:events:632:26)
    at Glob.emit (node:events:517:28)
    at Glob.emit (node:domain:489:12)
    at Glob._finish (/opt/temp/cv.git/node_modules/glob-stream/node_modules/glob/glob.js:194:8)
    at done (/opt/temp/cv.git/node_modules/glob-stream/node_modules/glob/glob.js:179:14)
    at Glob._processSimple2 (/opt/temp/cv.git/node_modules/glob-stream/node_modules/glob/glob.js:688:12)
    at /opt/temp/cv.git/node_modules/glob-stream/node_modules/glob/glob.js:676:10
    at Glob._stat2 (/opt/temp/cv.git/node_modules/glob-stream/node_modules/glob/glob.js:772:12)
    at lstatcb_ (/opt/temp/cv.git/node_modules/glob-stream/node_modules/glob/glob.js:764:12)`
`[17:17:53] 'build' errored after 232 ms`
`[17:17:50] DONE RECIPE: [ build ] [/opt/temp/cv.git/build-0.3.1-8-production]`

**Comment by unisharpUO** [comment]
had to install bower
